import Link from "next/link";
import { Card, CardContent } from "@/components/ui/card";
import { CalendarDays, CalendarRange, Users, LineChart } from "lucide-react";

const REPORTS = [
  {
    href: "/reports/daily",
    title: "Daily End of Day (EOD)",
    description: "Full breakdown of a single day's sales, collections, and profit.",
    icon: CalendarDays,
  },
  {
    href: "/reports/monthly",
    title: "Monthly Report",
    description: "Month-level revenue, profit, expense breakdown, and employee summary.",
    icon: CalendarRange,
  },
  {
    href: "/reports/employee-performance",
    title: "Employee Performance",
    description: "Bills, sales, and profit generated by each employee over a date range.",
    icon: Users,
  },
  {
    href: "/reports/profit-loss",
    title: "Profit & Loss",
    description: "Revenue, cost of goods sold, gross profit, expenses, and net profit.",
    icon: LineChart,
  },
];

export default function ReportsPage() {
  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-semibold text-primary">Reports</h1>
        <p className="text-sm text-primary/50">Printable, professionally formatted business reports.</p>
      </div>
      <div className="grid gap-4 sm:grid-cols-2">
        {REPORTS.map((r) => (
          <Link key={r.href} href={r.href}>
            <Card className="h-full transition-shadow hover:shadow-lg">
              <CardContent className="flex items-start gap-3">
                <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-primary/10 text-primary">
                  <r.icon className="h-5 w-5" />
                </div>
                <div>
                  <p className="font-medium text-primary">{r.title}</p>
                  <p className="mt-1 text-sm text-primary/50">{r.description}</p>
                </div>
              </CardContent>
            </Card>
          </Link>
        ))}
      </div>
    </div>
  );
}
